In [1]:
#Завдання 1, варіант 15
#Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та виведіть його значення.

import numpy as np
a = np.array([])

for num in range(2,70):
    prime = True
    for i in range(2,num):
        if (num%i==0):
            prime = False
    if prime:
        a = np.append(a, np.array([num]))

print("Матриця a:", a)

Матриця a: [ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29. 31. 37. 41. 43. 47. 53. 59. 61.
 67.]


In [2]:
#Завдання 2, варіант 15
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів перших натуральних чисел.

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = b**2
print("Матриця b:")
print(b)

Матриця b:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [3]:
#Завдання 3, варіант 15
#Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть максимальний елемент.

c = np.random.randint(-10,11, size=(5,5))
print("Матриця c:")
print(c)

print("Максимальний елемент: ", c.max())

Матриця c:
[[ -6 -10   9  -3   8]
 [  7  -3  -9  -2  -9]
 [ 10  -1  -6   8  -9]
 [ -3  10  -2  -8  -8]
 [  3  -9  -5  -2   7]]
Максимальний елемент:  10


In [4]:
#Завдання 4, варіант 15
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок,
#що містить максимальні елементи в кожному стовпці.

d = np.random.randint(0,2, size=(4,4))
print("Матриця d:")
print(d)

print("Рядок, що містить максимальні елементи: ", d.max(0))

Матриця d:
[[0 1 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 0 0 1]]
Рядок, що містить максимальні елементи:  [1 1 1 1]


In [5]:
#Завдання 5, варіант 15
#Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10
#та виконайте на них поелементні операції додавання, віднімання та множення.

e = np.random.randint(-10, 11, size=(7))
f = np.random.randint(-10, 11, size=(7))

print("Масив e:")
print(e)
print("Масив f:")
print(f)
print()

e = e+2
print("Масив e після додавання +2:")
print(e)
f = f+2
print("Масив f після додавання +2:")
print(f)
print()

e = e-3
print("Масив e після віднімання -3:")
print(e)
f = f-3
print("Масив f після додавання -3:")
print(f)
print()

e = e*2
print("Масив e після множення на 2:")
print(e)
f = f*2
print("Масив f після множення на 2:")
print(f)

Масив e:
[-10   9 -10  -5  -8  -6   7]
Масив f:
[-9 10 -1  8  7  1  6]

Масив e після додавання +2:
[-8 11 -8 -3 -6 -4  9]
Масив f після додавання +2:
[-7 12  1 10  9  3  8]

Масив e після віднімання -3:
[-11   8 -11  -6  -9  -7   6]
Масив f після додавання -3:
[-10   9  -2   7   6   0   5]

Масив e після множення на 2:
[-22  16 -22 -12 -18 -14  12]
Масив f після множення на 2:
[-20  18  -4  14  12   0  10]


In [6]:
#Завдання 6, варіант 15
#Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та знайдіть їх добуток.

g = np.random.randint(-10, 11, size=(4,4))
h = np.random.randint(-10, 11, size=(4,4))

print("Матриця g:")
print(g)
print("Матриця h:")
print(h)

gh = np.dot(g, h)
print("Добуток матриць g та h:")
print(gh)

Матриця g:
[[ -4   9   1   3]
 [ -2   5   0   9]
 [  7  10   7   7]
 [  7  -2 -10  -2]]
Матриця h:
[[ -3  -6   3   3]
 [ -4  -6  -8  -5]
 [-10  -2  -8   7]
 [ -1  -5   3   9]]
Добуток матриць g та h:
[[ -37  -47  -83  -23]
 [ -23  -63  -19   50]
 [-138 -151  -94   83]
 [  89    0  111  -57]]


In [8]:
#Завдання 7, варіант 15
#Створіть дві матриці розміром 4x2 та 2x2,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.

import numpy as np
i = np.random.randint(1, 4, size=(4,2))
j = np.random.randint(1, 4, size=(2,2))

print("Матриця i:")
print(i)
print("Матриця j:")
print(j)

ij = np.dot(i, j)
print("Добуток матриць i та j:")
print(ij)

Матриця i:
[[3 2]
 [2 1]
 [1 3]
 [1 3]]
Матриця j:
[[1 3]
 [2 1]]
Добуток матриць i та j:
[[ 7 11]
 [ 4  7]
 [ 7  6]
 [ 7  6]]


In [9]:
#Завдання 8, варіант 15
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
#від 1 до 7 та знайдіть її обернену матрицю

k = np.random.randint(1, 8, size=(2,2))

print("Матриця k:")
print(k)

k_inv = np.linalg.inv(k)
print("Обернена матриця k:")
print(k_inv)

Матриця k:
[[2 3]
 [2 2]]
Обернена матриця k:
[[-1.   1.5]
 [ 1.  -1. ]]


In [11]:
#Завдання 9, варіант 15
#Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні
#від 0 до 1 та транспонуйте її.

l = np.random.randint(0, 2, size=(3,5))

print("Матриця l:")
print(l)

l_tr = l.transpose()
print("Транспонована матриця l:")
print(l_tr)

Матриця l:
[[1 0 1 1 0]
 [0 0 1 1 0]
 [1 1 0 1 0]]
Транспонована матриця l:
[[1 0 1]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [0 0 0]]


In [12]:
#Завдання 10, варіант 15
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
#випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами
#в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

m = np.random.randint(0, 2, size=(3,4))
n = np.random.randint(1, 11, size=(4))

print("Матриця m:")
print(m)
print("Вектор n:")
print(n)

mn = np.dot(m, n)
print("Добуток матриці m та вектору n:")
print(mn)

Матриця m:
[[0 1 1 1]
 [1 1 0 1]
 [0 1 1 1]]
Вектор n:
[5 7 3 9]
Добуток матриці m та вектору n:
[19 21 19]


In [29]:
#Завдання 11, варіант 15
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
#випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору.

o = np.random.uniform(0, 1, size=(2,3))
p = np.random.uniform(0, 1, size=(3))
o = np.round(o, 2)
p = np.round(p, 2)

print("Матриця o:")
print(o)
print("Вектор p:")
print(p)

sum = 0
for i in range(len(o)):
    for j in range(len(p)):
        if (o[i][j] < p[j]):
            sum = sum + o[i][j]

print("Сума елементів матриці o, що менше за відповідний елемент вектору p:")
print(sum)

Матриця o:
[[0.65 0.14 0.94]
 [0.99 0.73 0.25]]
Вектор p:
[0.61 0.99 0.25]
Сума елементів матриці o, що менше за відповідний елемент вектору p:
0.87


In [30]:
#Завдання 12, варіант 15
#Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 10 та знайдіть їхню суму.

q = np.random.randint(1, 11, size=(8,8))
r = np.random.randint(1, 11, size=(8,8))

print("Матриця q:")
print(q)
print("Матриця r:")
print(r)

qr = q + r
print("Сума матриць q та r:")
print(qr)

Матриця q:
[[ 5  9  9  3 10  2 10  9]
 [ 5  9  5  8  8  9  6 10]
 [ 1  2  3  2  9  3  6 10]
 [ 7  5  7  7  6  4  6  1]
 [ 1  8  9  6  4 10  6  8]
 [ 1  5  4  6  5  6  7 10]
 [ 5  8  6  1  2 10  3  3]
 [ 6  5  9  9  4  5  7  5]]
Матриця r:
[[ 6 10  6  5  2  7  1  7]
 [ 8 10  2  6  1  3  2 10]
 [ 3  3  7 10 10 10  5  4]
 [ 8 10  7  8  7  2  3  4]
 [ 1  6  4  2  7  9  9  3]
 [ 2  5  3  3 10  3 10  1]
 [ 7  3  9 10  7  2  1  2]
 [ 2  4  9  4  8  4  1  7]]
Сума матриць q та r:
[[11 19 15  8 12  9 11 16]
 [13 19  7 14  9 12  8 20]
 [ 4  5 10 12 19 13 11 14]
 [15 15 14 15 13  6  9  5]
 [ 2 14 13  8 11 19 15 11]
 [ 3 10  7  9 15  9 17 11]
 [12 11 15 11  9 12  4  5]
 [ 8  9 18 13 12  9  8 12]]


In [32]:
#Завдання 13, варіант 15
#Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами
#в діапазоні від -1 до 1 та знайдіть добуток їх елементів.

s = np.random.uniform(-1, 1, size=(3,3))
t = np.random.uniform(-1, 1, size=(3,3))
s = np.round(s, 2)
t = np.round(t, 2)

print("Матриця s:")
print(s)
print("Матриця t:")
print(t)

st = np.dot(s, t)
print("Добуток матриць s та t:")
print(mn)

Матриця s:
[[ 0.62  0.52 -0.02]
 [-0.52 -0.36  0.45]
 [ 0.12  0.75  0.84]]
Матриця t:
[[ 0.73 -0.7   0.67]
 [ 0.05 -0.57 -0.59]
 [ 0.88 -0.59  0.93]]
Добуток матриць s та t:
[19 21 19]


In [37]:
#Завдання 14, варіант 15
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
#в діапазоні від -5 до 5 та знайдіть добуток елементів матриці, які більше
#за її середнє арифметичне значення.

u = np.random.randint(-5, 6, size=(3,3))

print("Матриця u:")
print(u)

u_mean = u.mean()
u_mean = np.round(u_mean, 2)
print("Середнє арифметичне значення матриці u:")
print(u_mean)

product = 1
for i in range(len(u)):
    for j in range(len(u)):
        if (u[i][j] > u_mean):
            product = product * u[i][j]

if (product == 1):
    print("У матриці u відсутні елементи, що більше за її середнє арифметичне значення")
else:
    print("Добуток елементів матриці u, що більше за її середнє арифметичне значення:")
    print(product)

Матриця u:
[[ 4  1  4]
 [ 1  5 -3]
 [-4  5  2]]
Середнє арифметичне значення матриці u:
1.67
Добуток елементів матриці u, що більше за її середнє арифметичне значення:
800


In [46]:
#Завдання 15, варіант 15
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
#в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик,
#що містить найбільше за модулем ціле значення в кожному рядку матриці.

v = np.random.uniform(-0.5, 0.5, size=(3,3))
v = np.round(v, 2)

print("Матриця v:")
print(v)

#Єдине можливе ціле число у її діапазоні від -0.5 до 0.5 - це число 0, при цьому вірогодіність його появи у матриці v вкрай низька.
#Для виконання завдання буде проведенно лише пошук найбільшого значення за модулем у кожному рядку матриці.
w = np.zeros((3))
for i in range(len(v)):
    w[i] = np.abs(v[i][0])
    for j in range(len(v)):
        if (np.abs(v[i][j]) > w[i]):
            w[i] = np.abs(v[i][j])

print("Вектор w, що містить найбільше за модулем значення з кожного рядку матриці v:")
print(w)

Матриця v:
[[ 0.07 -0.42  0.08]
 [ 0.03  0.4  -0.1 ]
 [-0.06  0.07 -0.01]]
Вектор w, що містить найбільше за модулем значення з кожного рядку матриці v:
[0.42 0.4  0.07]


In [ ]:
#Висновок
#У данній лабораторній роботі було дослідженно тему машинного навчання та елементів лінійної алгебри.
#Була проведена робота з основними функціями керування масивами та матрицями у Python, бібліотеками numpy та random.
#Результати роботи були завантажені на відповідний Github-репозиторій.